apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
    # Targets TCP port 9376 on any POD with the label app = MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  